2024-11-15T04:50:00...2024-11-15T06:03:00
http://github.com/KenAdeniji/WordEngineering/blob/main/IIS/WordEngineering/2018-05-03Correspondence/2024-11-14T0900JamesWong_-_XPHealthInc_-_james@xphealth.co_-_(206)839-6960_-_SanCarlos_-_California(CA)_-_AntonioErmírio_deMoraes_Neto.txt
http://github.com/KenAdeniji/WordEngineering/blob/main/IIS/WordEngineering/2018-05-03Correspondence/2024-11-14T0900JamesWong_-_XPHealthInc_-_james@xphealth.co_-_(206)839-6960_-_SanCarlos_-_California(CA)_-_AntonioErmirio_deMoraes_Neto.txt

Kehinde Adewumi Adeniji
Home telephone: (510) 796-8121
mailto:KenAdeniji@hotmail.com
http://www.JesusInTheLamb.com
4762 Canvasback Common
Fremont, California (CA) 94555
United States of America (USA)

James Wong
Antonio Ermírio de Moraes Neto
Company	XP Health Inc.
Work e-mail	james@xphealth.co
Work phone	(206) 839-6960
Work address	San Carlos, California (CA), United States of America (USA)
Website	sfbay.craigslist.org/pen/sof/d/san-carlos-product-engineer-position-at/7769179828.html
http://www.linkedin.com/pulse/how-covid-19-expanded-our-mission-helped-us-earn-fastcos-moraes

2024-11-14T09:00:00...2024-11-14T09:30:00 Telephone interview appointment

I waited for James Wong telephone call for several minutes, after the appointed time of 2024-11-14T09:00:00.

I finally telephoned James Wong on (206) 839-6960.

James Wong asked me to tell him about myself?

I told James Wong that my resume and doctoral dissertation are available on the Internet and I have sent both to him via e-mail.

I asked James Wong to tell me about his company, XP Health?

James Wong said we are a Series-B start-up. We employ between 13...15 engineers.

I told James Wong that since the age of 27 years old I have been a contract consultant, and I am now 57 years old.

James Wong asked would you say your programming language is .NET?

	http://KenAdeniji.WordPress.com/2015/12/06/2015-10-23doctoraldissertation
	http://KenAdeniji.WordPress.com/2015/11/20/ken-adenijis-resume

		Program Language: C#, C++, C, Visual Basic, Java, Go Language, PowerBuilder
		Script Language: ASP, ASP.NET, JavaScript, Python, R Language, PowerShell, GraphQL, PHP, Ruby

	http://github.com/KenAdeniji/WordEngineering/blob/main/IIS/WordEngineering/Resume/2020-04-17Skill.txt

James Wong asked about Australia?

2024-11-15T05:18:00 Wandering years, a generation, 2 years prior, 38 years after (Deuteronomy 2:14, Genesis 15:13).

2024-11-15T05:18:00	Urine downstairs west restroom.
	I am not a major asset...
	I am not a major asset... this is what I am?

2024-11-15T05:41:00...2024-11-15T05:50:00
D:\WordEngineering>git push
To https://github.com/KenAdeniji/WordEngineering
 ! [rejected]          main -> main (fetch first)
error: failed to push some refs to 'https://github.com/KenAdeniji/WordEngineering'
hint: Updates were rejected because the remote contains work that you do not
hint: have locally. This is usually caused by another repository pushing to
hint: the same ref. If you want to integrate the remote changes, use
hint: 'git pull' before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.

2024-11-15T05:57:00...2024-11-15T06:03:00
git pull
git push